### ISSUE TITLE
[bug](dapp): Upgrade tailwindcss v2 to v3 syntax

### ISSUE THREAD

**Issue by martines3000** [blockchain-lab-um/masca#244]
### Describe the bug

Most of the things are already built with v3, but there are some left over things still written in tailwindcss v2.

## TODO:

- [ ] [outline](https://tailwindcss.com/docs/upgrade-guide#outline-black-white) 
- [ ] [opacity](https://tailwindcss.com/docs/upgrade-guide#new-opacity-modifier-syntax) 
- [ ] Also check if I missed any other things to update in the linked guide
